flask_blog/__init__.py
# Copyright (c) 2020 samuele
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

flask_blog/app.py
# Copyright (c) 2020 samuele
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

from flask import Flask

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "postgresql://postgres:changeme@localhost/postgres"
app.secret_key = b'\x9b\xcf\x1d\x1f4sN\xaa\xb31\x89F\xa4\xe5\x1dK'

flask_blog/blueprints/__init__.py
# Copyright (c) 2020 samuele
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

flask_blog/blueprints/main.py
from flask import Blueprint, redirect, url_for, render_template, session, request
from ..database_model import db, Post
main = Blueprint("main", __name__)


@main.route("/")
def home():
    logged = False
    if "username" in session:
        logged = True
    current_page = int(request.args.get("page", default="1"))
    previous_page = max(1, current_page-2)
    pages = Post.query.paginate(current_page, 10)
    end_page = min(max(1, pages.pages), previous_page+5)

    return render_template("index.html",
                           logged=logged,
                           posts=pages.items,
                           start_page=previous_page,
                           end_page=end_page+1,
                           curr_page=current_page)


@main.route("/newpost", methods=["GET", "POST"])
def new_post():
    if request.method == "POST":
        username = session["username"]
        userid = session["userid"]
        image = request.form["image"]
        title = request.form["title"]
        content = request.form["content"]

        post = Post(
            image=image,
            title=title,
            content=content,
            author_name=username,
            author=int(userid)
        )
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("main.home"))
    return render_template("new_post.html")


@main.route("/post/<id>")
def post(id):
    post = Post.query.get(int(id))
    return render_template("post.html", post=post)

flask_blog/blueprints/sessionctrl.py
# Copyright (c) 2020 samuele
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

from flask import Blueprint, request, render_template, Response, abort, redirect, session, url_for
from ..database_model import User, db
from random import getrandbits
from hashlib import md5

blue = Blueprint("sessionctrl", __name__)


@blue.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form["username"]
        password: str = request.form["password"]
        csrf_form = request.form["csrf"]
        salt = getrandbits(128).to_bytes(16, 'little')
        salted_password = bytes(
            [b1 ^ b2 for b1, b2 in zip(password.encode(), salt)])
        csrf_cookie = request.cookies.get("csrf")
        if csrf_form != csrf_cookie:
            return abort(400, "CSRF Token mismatch")
        user = User(username=username,
                    password=md5(salted_password).hexdigest(),
                    salt=salt)

        db.session.add(user)
        db.session.commit()
        resp: Response = redirect(url_for('sessionctrl.login'))
        resp.delete_cookie("csrf")
    csrf = getrandbits(64)
    resp = Response(render_template('register.html', csrf=csrf))
    resp.set_cookie('csrf', str(csrf))
    return resp


@blue.route('/logout')
def logout():
    session.clear()
    return redirect(url_for("main.home"))


@blue.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password: str = request.form["password"]
        csrf_form = request.form["csrf"]
        csrf_cookie = request.cookies.get("csrf")
        if csrf_form != csrf_cookie:
            return abort(400, "CSRF Token mismatch")
        user = User.query.filter_by(username=username).first()
        if user is None:
            return "Wrong User or password", 400
        found_password = user.password
        salt = user.salt
        salted_password = bytes(
            [b1 ^ b2 for b1, b2 in zip(password.encode(), salt)])
        if md5(salted_password).hexdigest() != found_password:
            return "User or Password"
        session["username"] = username
        session["userid"] = user.id
        return redirect(url_for('main.home'))
    csrf = getrandbits(64)
    resp = Response(render_template('login.html', csrf=csrf))
    resp.set_cookie('csrf', str(csrf))
    return resp

flask_blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}"> {% block styles %} {% endblock styles %}
    <title>{% block title %} {% endblock title %}</title>
    {% endblock head %}
</head>

<body>
    <div id="page">
        <div id="header">
            <img src="{{ url_for('static', filename='img/logo.svg') }}" width="50rem">
            <div class="left">
                <h1>Flask Blog</h1>
            </div>
            <div class="center"></div>
            <div class="right">
                {% if logged %}
                <a href="{{ url_for('main.new_post') }}" class="button success">New Post</a>
                <a href="{{ url_for('sessionctrl.logout') }}" class="button error">Logout</a>{% else %}
                <a href="{{ url_for('sessionctrl.login') }}" class="button">Login</a>
                <a href="{{ url_for('sessionctrl.register') }}" class="button">Register</a> {% endif %}
            </div>

        </div>
        <div id="desk-menu">
            <div class="items">
                <a href="{{ url_for('main.home') }}" class=" item {% if location == 'home'  %}
                    active
                {% endif %} ">Home</a>
                <a href="{{ url_for('main.home') }}" class=" item ">About</a>
                <a href="{{ url_for('main.home') }}" class=" item ">Getting Started</a>
            </div>

            <form action="/Todo" method="GET">
                <label><input type=" text " name=" query " placeholder="Search" /></label>
            </form>

        </div>

        <div id="content">
            {% block content %} {% endblock content %}
        </div>

    </div>
</body>

</html>

flask_blog/templates/index.html
{% set location = "home" %} {% extends 'base.html' %} {% block title %} Flask Blog {% endblock title %} {% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}"> {% endblock styles %} {% block content %}
<div class="left">
    <div id="post-container">
        {% for post in posts %}
        <article class="post" id="{{post.id}}">
            <div class="post-image">
                <a href="/article/id"><img src="{{ post.image }}"></a>
            </div>
            <div class="main">
                <div class="top"><a href="{{ url_for('main.post', id=post.id) }}">{{ post.title }}</a></div>
                <div class="bottom">{{post.content|safe|truncate(500)}}</div>
                <div class="author">Author: {{post.author_name}}</div>
            </div>
        </article>
        {% endfor %}
    </div>
</div>
<div class="right">
    <div id="tabs-buttons">
        {% for index in range(start_page,end_page) %}
        <a href="{{ url_for('main.home', page=index) }}" class="page {% if curr_page == index %}
            current
        {% endif %} button ">{{index}}</a> {% endfor %}
    </div>
    <ul>
        {% for post in posts %}
        <li>
            <a href="#{{post.id}}">{{post.title}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

flask_blog/templates/login.html
{% extends 'base.html' %} {% block title %} Login {% endblock title %} {% block content %}
<form action="{{ url_for('sessionctrl.login') }}" method="post">
    <h1>Login</h1>
    <input type="hidden" name="csrf" value="{{csrf}}">
    <label>
        Username
        <input type="text" name="username" id="username" />
    </label>
    <label>
        Password
        <input type="password" name="password" id="password" />
    </label>
    <input type="submit" value="Login">
</form>
{% endblock content %}

flask_blog/templates/new_post.html
{% extends 'base.html' %} {% block title %} New Post {% endblock title %} {% block content %}
<form action="{{ url_for('main.new_post') }}" method="post">
    <h1>New Post</h1>
    <label>
        Title
        <input type="text" name="title" id="title">
    </label>
    <label>
        Image
        <input type="text" name="image" id="image">
    </label>
    <label>
        Content
        <textarea name="content" id="content" style="margin:0;" rows="10"></textarea>
    </label>
    <input type="submit" value="Post">
</form>
{% endblock content %}

flask_blog/templates/post.html
{% extends 'base.html' %} {% block title %} {{post.title}} {% endblock title %} {% block content %}

<h1>{{post.title}}</h1>
<p>{{post.content}}</p>
{% endblock content %}

flask_blog/templates/register.html
{% extends 'base.html' %} {% block title %} Register {% endblock title %} {% block content %}
<form action="{{ url_for('sessionctrl.register') }}" method="post">
    <h1>Register</h1>
    <input type="hidden" name="csrf" value="{{csrf}}">
    <label>
        Username
        <input type="text" name="username" id="username" />
    </label>
    <label>
        Password
        <input type="password" name="password" id="password" />
    </label>
    <input type="submit" value="Register">
</form>
{% endblock content %}